### ISSUE TITLE
دریافت ماه قبل

### ISSUE THREAD

**Issue by imi24** [samanzamani/PersianDate#43]
خیلی لایبرری خوبی بود ممنون از زحماتتان
وقتی میخواییم یک ماه  کم کنیم 
`pdate.addMonth(-1);`
باید استفاده کنیم که کار نمیکنه

ما الان با این روش ماه قبل را دریافت میکنم . 
`int monthSh = pdate.getShMonth();
if (monthSh == 1) {
monthSh = 12;
} else {
    monthSh--;
}`

**Comment by samanzamani** [comment]
سلام
در نسخه جدید متد ماهش ماه اضافه خواهد شد
subMonth

**Comment by mahramane** [comment]
> خیلی لایبرری خوبی بود ممنون از زحماتتان
> وقتی میخواییم یک ماه کم کنیم
> `pdate.addMonth(-1);`
> باید استفاده کنیم که کار نمیکنه
> 
> ما الان با این روش ماه قبل را دریافت میکنم .
> `int monthSh = pdate.getShMonth(); if (monthSh == 1) { monthSh = 12; } else { monthSh--; }`

این کد مثل تابع pdate.addMonth(1) عمل نمیکنه
تابع addMonth بر روی کل تاریخ تاثیر میزاره یعنی در صورتی که به اسفند سال 1399 یک ماه اضافه کنی میشه فروردین سال 1400
اما تابع شما میشه فروردین همون سال 99 
من از کد زیر برای دریافت ماه قبل استفاده کردم
val pDate = PersianDate().initJalaliDate(1399, 12, 0)
pDate.shMonth
pDate.monthName()
الان من ماه اسفند رو توی تاریخ وارد کردم ولی چون روز رو 0 وارد کردم توابع shMonth و monthName() ماه بهمن رو برمیگردونن
آقای زمانی لطفا  در هر صورت تابع removMonth اضافه کنید
باتشکر

**Comment by samanzamani** [comment]
سلام
با تشکر از نظر شما
در اپدیت بعد اضافه خواهد شد

**Comment by samanzamani** [comment]
Since v1.4.0 you can get the former date with the below methods:

- subDate(long SubYear, long SubMonth, long SubDay, long SubHour, long SubMinute,
      long SubSecond) [code](https://github.com/samanzamani/PersianDate/blob/master/persiandate/src/main/java/saman/zamani/persiandate/PersianDate.java#L627-L674)
- subDate(long SubYear, long SubMonth, long SubDay) [code](https://github.com/samanzamani/PersianDate/blob/master/persiandate/src/main/java/saman/zamani/persiandate/PersianDate.java#L676-L685)
- subYears(int years) //Subtract year
- subYear() //Subtract a year
- subMonths(int months)
- subMonth()
- subDays(int days)
- subDay()
- subHours(int hours)
- subHour()
- subMinutes(int minutes)
- subMinute()
- subSeconds(int seconds)
- subSecond()
